apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tstest2
  description: tap-workload-description
  tags:
  - v1alpha1
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=tstest2
spec:
  type: service
  lifecycle: production
  owner: default-org
  system: unknown
